# AULA 06 13-11-2019 - # TRABALHANDO COM LISTAS

# LISTAS SÃO COLEÇÕES MISTAS DE OBJETOS QUE PODEM SER DE QUALQUER TIPO, ATÉ OUTRAS LISTAS.
# AS LISTAS DO PYTHON SÃO MUTÁVEIS E PODEM SER ALTERADAS A QUALQUER INSTANTE.

#--- CRIANDO UMA LISTA VAZIA

lista1 = []

#--- CRIANDO UMA LISTA COM ITENS DO TIPO STRING

lista2 = ['banana','maçã','pera']

# --- CRIANDO UMA LISTA COM ITENS NA FORMA INT

lista3 = [1,2,3,4,5]

#--- ADICIONANDO ELEMENTOS A UMA LISTA JA DEFINIDA

lista1.append('melancia') # O MÉTODO .APPEND ACEITA APENAS UM OBJETO POR VEZ A SER ADICIONADO

#--- CRIANDO LISTAS COM DADOS DA FUNÇÃO INPUT

lista4 = [input('Digite seu nome'), input('Digite seu sobrenome: '), int(input('Digite sua idade: '))] # ELEMENTOS MISTOS 

#--- RECUPERANO UM DADOS DE DETERMINADA LISTA

print(lista1[2]) #VAI IMPRIMIR 'PERA' POIS A CONTAGEM DAS LISTAS COMEÇAM NO ZERO. 

